/*
 * Additional public IPTV playlists and curated direct channels.
 * Extracted from freeTvPlaylist.js so that file stays under the edit limit.
 * All entries follow the same shape as LIVE_TV_SOURCES and
 * PUBLIC_DIRECT_CHANNELS in freeTvPlaylist.js.
 */

export const ADDITIONAL_LIVE_TV_SOURCES = [
  {
    id: "iptv-org-us",
    name: "IPTV-org United States",
    url: "https://iptv-org.github.io/iptv/countries/us.m3u",
    priority: 78,
    category: "United States",
    country: "US",
  },
  {
    id: "iptv-org-de",
    name: "IPTV-org Germany",
    url: "https://iptv-org.github.io/iptv/countries/de.m3u",
    priority: 72,
    category: "Germany",
    country: "DE",
  },
  {
    id: "iptv-org-es",
    name: "IPTV-org Spain",
    url: "https://iptv-org.github.io/iptv/countries/es.m3u",
    priority: 72,
    category: "Spain",
    country: "ES",
  },
  {
    id: "iptv-org-it",
    name: "IPTV-org Italy",
    url: "https://iptv-org.github.io/iptv/countries/it.m3u",
    priority: 72,
    category: "Italy",
    country: "IT",
  },
  {
    id: "iptv-org-in",
    name: "IPTV-org India",
    url: "https://iptv-org.github.io/iptv/countries/in.m3u",
    priority: 71,
    category: "India",
    country: "IN",
  },
  {
    id: "iptv-org-tr",
    name: "IPTV-org Turkey",
    url: "https://iptv-org.github.io/iptv/countries/tr.m3u",
    priority: 70,
    category: "Turkey",
    country: "TR",
  },
  {
    id: "iptv-org-ae",
    name: "IPTV-org UAE",
    url: "https://iptv-org.github.io/iptv/countries/ae.m3u",
    priority: 70,
    category: "United Arab Emirates",
    country: "AE",
  },
  {
    id: "iptv-org-jp",
    name: "IPTV-org Japan",
    url: "https://iptv-org.github.io/iptv/countries/jp.m3u",
    priority: 70,
    category: "Japan",
    country: "JP",
  },
  {
    id: "iptv-org-kr",
    name: "IPTV-org South Korea",
    url: "https://iptv-org.github.io/iptv/countries/kr.m3u",
    priority: 69,
    category: "South Korea",
    country: "KR",
  },
  {
    id: "iptv-org-br",
    name: "IPTV-org Brazil",
    url: "https://iptv-org.github.io/iptv/countries/br.m3u",
    priority: 69,
    category: "Brazil",
    country: "BR",
  },
  {
    id: "iptv-org-mx",
    name: "IPTV-org Mexico",
    url: "https://iptv-org.github.io/iptv/countries/mx.m3u",
    priority: 68,
    category: "Mexico",
    country: "MX",
  },
  {
    id: "iptv-org-fr",
    name: "IPTV-org France",
    url: "https://iptv-org.github.io/iptv/countries/fr.m3u",
    priority: 72,
    category: "France",
    country: "FR",
  },
  {
    id: "iptv-org-nl",
    name: "IPTV-org Netherlands",
    url: "https://iptv-org.github.io/iptv/countries/nl.m3u",
    priority: 70,
    category: "Netherlands",
    country: "NL",
  },
  {
    id: "iptv-org-se",
    name: "IPTV-org Sweden",
    url: "https://iptv-org.github.io/iptv/countries/se.m3u",
    priority: 69,
    category: "Sweden",
    country: "SE",
  },
  {
    id: "iptv-org-no",
    name: "IPTV-org Norway",
    url: "https://iptv-org.github.io/iptv/countries/no.m3u",
    priority: 68,
    category: "Norway",
    country: "NO",
  },
  {
    id: "iptv-org-dk",
    name: "IPTV-org Denmark",
    url: "https://iptv-org.github.io/iptv/countries/dk.m3u",
    priority: 68,
    category: "Denmark",
    country: "DK",
  },
  {
    id: "iptv-org-fi",
    name: "IPTV-org Finland",
    url: "https://iptv-org.github.io/iptv/countries/fi.m3u",
    priority: 67,
    category: "Finland",
    country: "FI",
  },
  {
    id: "iptv-org-pl",
    name: "IPTV-org Poland",
    url: "https://iptv-org.github.io/iptv/countries/pl.m3u",
    priority: 68,
    category: "Poland",
    country: "PL",
  },
  {
    id: "iptv-org-gr",
    name: "IPTV-org Greece",
    url: "https://iptv-org.github.io/iptv/countries/gr.m3u",
    priority: 67,
    category: "Greece",
    country: "GR",
  },
  {
    id: "iptv-org-pt",
    name: "IPTV-org Portugal",
    url: "https://iptv-org.github.io/iptv/countries/pt.m3u",
    priority: 67,
    category: "Portugal",
    country: "PT",
  },
  {
    id: "iptv-org-ch",
    name: "IPTV-org Switzerland",
    url: "https://iptv-org.github.io/iptv/countries/ch.m3u",
    priority: 68,
    category: "Switzerland",
    country: "CH",
  },
  {
    id: "iptv-org-at",
    name: "IPTV-org Austria",
    url: "https://iptv-org.github.io/iptv/countries/at.m3u",
    priority: 67,
    category: "Austria",
    country: "AT",
  },
  {
    id: "iptv-org-be",
    name: "IPTV-org Belgium",
    url: "https://iptv-org.github.io/iptv/countries/be.m3u",
    priority: 67,
    category: "Belgium",
    country: "BE",
  },
  {
    id: "iptv-org-za",
    name: "IPTV-org South Africa",
    url: "https://iptv-org.github.io/iptv/countries/za.m3u",
    priority: 68,
    category: "South Africa",
    country: "ZA",
  },
  {
    id: "iptv-org-ng",
    name: "IPTV-org Nigeria",
    url: "https://iptv-org.github.io/iptv/countries/ng.m3u",
    priority: 67,
    category: "Nigeria",
    country: "NG",
  },
  {
    id: "iptv-org-eg",
    name: "IPTV-org Egypt",
    url: "https://iptv-org.github.io/iptv/countries/eg.m3u",
    priority: 66,
    category: "Egypt",
    country: "EG",
  },
  {
    id: "iptv-org-sa",
    name: "IPTV-org Saudi Arabia",
    url: "https://iptv-org.github.io/iptv/countries/sa.m3u",
    priority: 66,
    category: "Saudi Arabia",
    country: "SA",
  },
  {
    id: "iptv-org-th",
    name: "IPTV-org Thailand",
    url: "https://iptv-org.github.io/iptv/countries/th.m3u",
    priority: 66,
    category: "Thailand",
    country: "TH",
  },
  {
    id: "iptv-org-id",
    name: "IPTV-org Indonesia",
    url: "https://iptv-org.github.io/iptv/countries/id.m3u",
    priority: 66,
    category: "Indonesia",
    country: "ID",
  },
  {
    id: "iptv-org-ph",
    name: "IPTV-org Philippines",
    url: "https://iptv-org.github.io/iptv/countries/ph.m3u",
    priority: 65,
    category: "Philippines",
    country: "PH",
  },
  {
    id: "iptv-org-pk",
    name: "IPTV-org Pakistan",
    url: "https://iptv-org.github.io/iptv/countries/pk.m3u",
    priority: 67,
    category: "Pakistan",
    country: "PK",
  },
  {
    id: "iptv-org-bd",
    name: "IPTV-org Bangladesh",
    url: "https://iptv-org.github.io/iptv/countries/bd.m3u",
    priority: 66,
    category: "Bangladesh",
    country: "BD",
  },
  {
    id: "iptv-org-lk",
    name: "IPTV-org Sri Lanka",
    url: "https://iptv-org.github.io/iptv/countries/lk.m3u",
    priority: 65,
    category: "Sri Lanka",
    country: "LK",
  },
  {
    id: "iptv-org-ar",
    name: "IPTV-org Argentina",
    url: "https://iptv-org.github.io/iptv/countries/ar.m3u",
    priority: 66,
    category: "Argentina",
    country: "AR",
  },
  {
    id: "iptv-org-cl",
    name: "IPTV-org Chile",
    url: "https://iptv-org.github.io/iptv/countries/cl.m3u",
    priority: 65,
    category: "Chile",
    country: "CL",
  },
  {
    id: "iptv-org-co",
    name: "IPTV-org Colombia",
    url: "https://iptv-org.github.io/iptv/countries/co.m3u",
    priority: 65,
    category: "Colombia",
    country: "CO",
  },
  {
    id: "iptv-org-pe",
    name: "IPTV-org Peru",
    url: "https://iptv-org.github.io/iptv/countries/pe.m3u",
    priority: 64,
    category: "Peru",
    country: "PE",
  },
  {
    id: "iptv-org-ve",
    name: "IPTV-org Venezuela",
    url: "https://iptv-org.github.io/iptv/countries/ve.m3u",
    priority: 64,
    category: "Venezuela",
    country: "VE",
  },
  {
    id: "iptv-org-religious",
    name: "IPTV-org Religious",
    url: "https://iptv-org.github.io/iptv/categories/religious.m3u",
    priority: 60,
    category: "Religious",
  },
  {
    id: "iptv-org-business",
    name: "IPTV-org Business",
    url: "https://iptv-org.github.io/iptv/categories/business.m3u",
    priority: 60,
    category: "Business",
  },
  {
    id: "iptv-org-cultural",
    name: "IPTV-org Cultural",
    url: "https://iptv-org.github.io/iptv/categories/cultural.m3u",
    priority: 60,
    category: "Cultural",
  },
  {
    id: "iptv-org-outdoor",
    name: "IPTV-org Outdoor",
    url: "https://iptv-org.github.io/iptv/categories/outdoor.m3u",
    priority: 60,
    category: "Outdoor",
  },
  {
    id: "iptv-org-fashion",
    name: "IPTV-org Fashion",
    url: "https://iptv-org.github.io/iptv/categories/fashion.m3u",
    priority: 58,
    category: "Fashion",
  },
  {
    id: "iptv-org-auto",
    name: "IPTV-org Auto",
    url: "https://iptv-org.github.io/iptv/categories/auto.m3u",
    priority: 58,
    category: "Auto",
  },
];

export const ADDITIONAL_PUBLIC_DIRECT_CHANNELS = [
  {
    id: "RedBullTV.at@Direct",
    tvgId: "RedBullTV.at",
    name: "Red Bull TV",
    logo: "https://i.imgur.com/UjJL6IY.png",
    url: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
    category: "Sports",
    country: "AT",
    priority: 90,
    sourceName: "Red Bull TV Public",
    kind: "direct",
  },
  {
    id: "NHKWorldJapan.jp@Direct",
    tvgId: "NHKWorldJapan.jp",
    name: "NHK World Japan",
    logo: "https://i.imgur.com/q3Zg3K2.png",
    url: "https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index.m3u8",
    category: "News",
    country: "JP",
    priority: 89,
    sourceName: "NHK World Public",
    kind: "direct",
  },
  {
    id: "NHKWorldJapan.jp@Official",
    tvgId: "NHKWorldJapan.jp",
    name: "NHK World Japan",
    url: "https://www3.nhk.or.jp/nhkworld/en/live/",
    category: "News",
    country: "JP",
    priority: 88,
    sourceName: "NHK World Official",
    officialUrl: "https://www3.nhk.or.jp/nhkworld/en/live/",
    officialLabel: "Open NHK World Live",
    kind: "external",
  },
  {
    id: "TRTWorld.tr@Official",
    tvgId: "TRTWorld.tr",
    name: "TRT World",
    url: "https://www.trtworld.com/live",
    category: "News",
    country: "TR",
    priority: 88,
    sourceName: "TRT World Official",
    officialUrl: "https://www.trtworld.com/live",
    officialLabel: "Open TRT World Live",
    kind: "external",
  },
  {
    id: "CGTNEnglish.cn@Official",
    tvgId: "CGTNEnglish.cn",
    name: "CGTN English",
    url: "https://www.cgtn.com/live/",
    category: "News",
    country: "CN",
    priority: 87,
    sourceName: "CGTN Official",
    officialUrl: "https://www.cgtn.com/live/",
    officialLabel: "Open CGTN Live",
    kind: "external",
  },
  {
    id: "RTNews.ru@Official",
    tvgId: "RTNews.ru",
    name: "RT News",
    url: "https://www.rt.com/on-air/",
    category: "News",
    country: "RU",
    priority: 80,
    sourceName: "RT Official",
    officialUrl: "https://www.rt.com/on-air/",
    officialLabel: "Open RT Live",
    kind: "external",
  },
  {
    id: "SkyNewsArabia.ae@Official",
    tvgId: "SkyNewsArabia.ae",
    name: "Sky News Arabia",
    url: "https://www.skynewsarabia.com/live/",
    category: "News",
    country: "AE",
    priority: 86,
    sourceName: "Sky News Arabia Official",
    officialUrl: "https://www.skynewsarabia.com/live/",
    officialLabel: "Open Sky News Arabia Live",
    kind: "external",
  },
  {
    id: "AlArabyTV.uk@Official",
    tvgId: "AlArabyTV.uk",
    name: "Al Araby TV",
    url: "https://www.alaraby.tv/live",
    category: "News",
    country: "GB",
    priority: 82,
    sourceName: "Al Araby Official",
    officialUrl: "https://www.alaraby.tv/live",
    officialLabel: "Open Al Araby Live",
    kind: "external",
  },
  {
    id: "AfricaNewsEnglish.be@Official",
    tvgId: "AfricaNewsEnglish.be",
    name: "Africa News English",
    url: "https://www.africanews.com/live/",
    category: "News",
    country: "BE",
    priority: 84,
    sourceName: "Africa News Official",
    officialUrl: "https://www.africanews.com/live/",
    officialLabel: "Open Africa News Live",
    kind: "external",
  },
  {
    id: "ABCNewsLive.us@Official",
    tvgId: "ABCNewsLive.us",
    name: "ABC News Live",
    url: "https://abcnews.go.com/live",
    category: "News",
    country: "US",
    priority: 88,
    sourceName: "ABC News Official",
    officialUrl: "https://abcnews.go.com/live",
    officialLabel: "Open ABC News Live",
    kind: "external",
  },
  {
    id: "CBSNews.us@Official",
    tvgId: "CBSNews.us",
    name: "CBS News",
    url: "https://www.cbsnews.com/live/",
    category: "News",
    country: "US",
    priority: 87,
    sourceName: "CBS News Official",
    officialUrl: "https://www.cbsnews.com/live/",
    officialLabel: "Open CBS News Live",
    kind: "external",
  },
  {
    id: "NBCNewsNow.us@Official",
    tvgId: "NBCNewsNow.us",
    name: "NBC News Now",
    url: "https://www.nbcnews.com/now",
    category: "News",
    country: "US",
    priority: 86,
    sourceName: "NBC News Official",
    officialUrl: "https://www.nbcnews.com/now",
    officialLabel: "Open NBC News Now",
    kind: "external",
  },
  {
    id: "BloombergTV.us@Official",
    tvgId: "BloombergTV.us",
    name: "Bloomberg TV",
    url: "https://www.bloomberg.com/live",
    category: "Business",
    country: "US",
    priority: 86,
    sourceName: "Bloomberg Official",
    officialUrl: "https://www.bloomberg.com/live",
    officialLabel: "Open Bloomberg Live",
    kind: "external",
  },
  {
    id: "CheddarNews.us@Official",
    tvgId: "CheddarNews.us",
    name: "Cheddar News",
    url: "https://www.cheddar.com/live",
    category: "Business",
    country: "US",
    priority: 80,
    sourceName: "Cheddar Official",
    officialUrl: "https://www.cheddar.com/live",
    officialLabel: "Open Cheddar Live",
    kind: "external",
  },
  {
    id: "ABCNewsLive.au@Official",
    tvgId: "ABCNewsLive.au",
    name: "ABC News Australia",
    url: "https://www.abc.net.au/news/newschannel/",
    category: "News",
    country: "AU",
    priority: 85,
    sourceName: "ABC Australia Official",
    officialUrl: "https://www.abc.net.au/news/newschannel/",
    officialLabel: "Open ABC News Australia",
    kind: "external",
  },
  {
    id: "SkyNewsAustralia.au@Official",
    tvgId: "SkyNewsAustralia.au",
    name: "Sky News Australia",
    url: "https://www.skynews.com.au/live",
    category: "News",
    country: "AU",
    priority: 84,
    sourceName: "Sky News Australia Official",
    officialUrl: "https://www.skynews.com.au/live",
    officialLabel: "Open Sky News Australia Live",
    kind: "external",
  },
  {
    id: "CNA.sg@Official",
    tvgId: "CNA.sg",
    name: "Channel NewsAsia",
    url: "https://www.channelnewsasia.com/live",
    category: "News",
    country: "SG",
    priority: 85,
    sourceName: "CNA Official",
    officialUrl: "https://www.channelnewsasia.com/live",
    officialLabel: "Open CNA Live",
    kind: "external",
  },
  {
    id: "WION.in@Official",
    tvgId: "WION.in",
    name: "WION (World is One News)",
    url: "https://www.wionews.com/live-tv",
    category: "News",
    country: "IN",
    priority: 84,
    sourceName: "WION Official",
    officialUrl: "https://www.wionews.com/live-tv",
    officialLabel: "Open WION Live",
    kind: "external",
  },
  {
    id: "NDTVIndia.in@Official",
    tvgId: "NDTVIndia.in",
    name: "NDTV India",
    url: "https://www.ndtv.com/live",
    category: "News",
    country: "IN",
    priority: 83,
    sourceName: "NDTV Official",
    officialUrl: "https://www.ndtv.com/live",
    officialLabel: "Open NDTV Live",
    kind: "external",
  },
  {
    id: "IndiaToday.in@Official",
    tvgId: "IndiaToday.in",
    name: "India Today",
    url: "https://www.indiatoday.in/livetv",
    category: "News",
    country: "IN",
    priority: 82,
    sourceName: "India Today Official",
    officialUrl: "https://www.indiatoday.in/livetv",
    officialLabel: "Open India Today Live",
    kind: "external",
  },
  {
    id: "AajTak.in@Official",
    tvgId: "AajTak.in",
    name: "Aaj Tak",
    url: "https://www.aajtak.in/livetv",
    category: "News",
    country: "IN",
    priority: 81,
    sourceName: "Aaj Tak Official",
    officialUrl: "https://www.aajtak.in/livetv",
    officialLabel: "Open Aaj Tak Live",
    kind: "external",
  },
  {
    id: "ABPNews.in@Official",
    tvgId: "ABPNews.in",
    name: "ABP News",
    url: "https://news.abplive.com/live-tv",
    category: "News",
    country: "IN",
    priority: 80,
    sourceName: "ABP News Official",
    officialUrl: "https://news.abplive.com/live-tv",
    officialLabel: "Open ABP News Live",
    kind: "external",
  },
  {
    id: "GeoNews.pk@Official",
    tvgId: "GeoNews.pk",
    name: "Geo News",
    url: "https://www.geo.tv/live",
    category: "News",
    country: "PK",
    priority: 82,
    sourceName: "Geo News Official",
    officialUrl: "https://www.geo.tv/live",
    officialLabel: "Open Geo News Live",
    kind: "external",
  },
  {
    id: "DawnNews.pk@Official",
    tvgId: "DawnNews.pk",
    name: "Dawn News",
    url: "https://www.dawnnews.tv/live",
    category: "News",
    country: "PK",
    priority: 81,
    sourceName: "Dawn News Official",
    officialUrl: "https://www.dawnnews.tv/live",
    officialLabel: "Open Dawn News Live",
    kind: "external",
  },
  {
    id: "SomoyNews.bd@Official",
    tvgId: "SomoyNews.bd",
    name: "Somoy News",
    url: "https://www.somoy.tv/news/live",
    category: "News",
    country: "BD",
    priority: 80,
    sourceName: "Somoy News Official",
    officialUrl: "https://www.somoy.tv/news/live",
    officialLabel: "Open Somoy News Live",
    kind: "external",
  },
  {
    id: "GlobeNews.gh@Official",
    tvgId: "GlobeNews.gh",
    name: "Ghana Globe News",
    url: "https://www.gbcghanaonline.com/live/",
    category: "News",
    country: "GH",
    priority: 78,
    sourceName: "GBC Ghana Official",
    officialUrl: "https://www.gbcghanaonline.com/live/",
    officialLabel: "Open GBC Ghana Live",
    kind: "external",
  },
  {
    id: "SABCNews.za@Official",
    tvgId: "SABCNews.za",
    name: "SABC News",
    url: "https://www.sabcnews.com/sabcnews/live/",
    category: "News",
    country: "ZA",
    priority: 80,
    sourceName: "SABC News Official",
    officialUrl: "https://www.sabcnews.com/sabcnews/live/",
    officialLabel: "Open SABC News Live",
    kind: "external",
  },
  {
    id: "eNCA.za@Official",
    tvgId: "eNCA.za",
    name: "eNCA",
    url: "https://www.enca.com/live",
    category: "News",
    country: "ZA",
    priority: 79,
    sourceName: "eNCA Official",
    officialUrl: "https://www.enca.com/live",
    officialLabel: "Open eNCA Live",
    kind: "external",
  },
  {
    id: "TVCNews.ng@Official",
    tvgId: "TVCNews.ng",
    name: "TVC News",
    url: "https://www.tvcnews.tv/live/",
    category: "News",
    country: "NG",
    priority: 80,
    sourceName: "TVC News Official",
    officialUrl: "https://www.tvcnews.tv/live/",
    officialLabel: "Open TVC News Live",
    kind: "external",
  },
  {
    id: "Arirang.kr@Official",
    tvgId: "Arirang.kr",
    name: "Arirang TV",
    url: "https://www.arirang.com/live",
    category: "News",
    country: "KR",
    priority: 82,
    sourceName: "Arirang Official",
    officialUrl: "https://www.arirang.com/live",
    officialLabel: "Open Arirang Live",
    kind: "external",
  },
  {
    id: "KBSWorld.kr@Official",
    tvgId: "KBSWorld.kr",
    name: "KBS World",
    url: "https://www.kbsworld.tv/live/",
    category: "General",
    country: "KR",
    priority: 81,
    sourceName: "KBS World Official",
    officialUrl: "https://www.kbsworld.tv/live/",
    officialLabel: "Open KBS World Live",
    kind: "external",
  },
  {
    id: "TV5Monde.fr@Official",
    tvgId: "TV5Monde.fr",
    name: "TV5Monde",
    url: "https://www.tv5monde.com/tv/direct",
    category: "General",
    country: "FR",
    priority: 80,
    sourceName: "TV5Monde Official",
    officialUrl: "https://www.tv5monde.com/tv/direct",
    officialLabel: "Open TV5Monde Live",
    kind: "external",
  },
  {
    id: "BFMTV.fr@Official",
    tvgId: "BFMTV.fr",
    name: "BFM TV",
    url: "https://www.bfmtv.com/en-direct/",
    category: "News",
    country: "FR",
    priority: 82,
    sourceName: "BFM TV Official",
    officialUrl: "https://www.bfmtv.com/en-direct/",
    officialLabel: "Open BFM TV Live",
    kind: "external",
  },
  {
    id: "LCP.fr@Official",
    tvgId: "LCP.fr",
    name: "LCP Assemblée Nationale",
    url: "https://www.lcp.fr/direct",
    category: "News",
    country: "FR",
    priority: 76,
    sourceName: "LCP Official",
    officialUrl: "https://www.lcp.fr/direct",
    officialLabel: "Open LCP Live",
    kind: "external",
  },
  {
    id: "Phoenix.de@Official",
    tvgId: "Phoenix.de",
    name: "Phoenix",
    url: "https://www.phoenix.de/livestream",
    category: "News",
    country: "DE",
    priority: 78,
    sourceName: "Phoenix Official",
    officialUrl: "https://www.phoenix.de/livestream",
    officialLabel: "Open Phoenix Live",
    kind: "external",
  },
  {
    id: "Tagesschau24.de@Official",
    tvgId: "Tagesschau24.de",
    name: "tagesschau24",
    url: "https://www.tagesschau.de/live/",
    category: "News",
    country: "DE",
    priority: 80,
    sourceName: "ARD Official",
    officialUrl: "https://www.tagesschau.de/live/",
    officialLabel: "Open tagesschau24 Live",
    kind: "external",
  },
  {
    id: "DWGerman.de@Official",
    tvgId: "DWGerman.de",
    name: "DW Deutsch",
    url: "https://www.dw.com/de/live-tv/channel-german",
    category: "News",
    country: "DE",
    priority: 84,
    sourceName: "DW Official",
    officialUrl: "https://www.dw.com/de/live-tv/channel-german",
    officialLabel: "Open DW Deutsch Live",
    kind: "external",
  },
  {
    id: "RAIItalia.it@Official",
    tvgId: "RAIItalia.it",
    name: "RAI Italia",
    url: "https://www.raiplay.it/dirette/",
    category: "General",
    country: "IT",
    priority: 78,
    sourceName: "RAI Official",
    officialUrl: "https://www.raiplay.it/dirette/",
    officialLabel: "Open RAI Live",
    kind: "external",
  },
  {
    id: "Antena3.es@Official",
    tvgId: "Antena3.es",
    name: "Antena 3",
    url: "https://www.antena3.com/directo",
    category: "General",
    country: "ES",
    priority: 78,
    sourceName: "Antena 3 Official",
    officialUrl: "https://www.antena3.com/directo",
    officialLabel: "Open Antena 3 Live",
    kind: "external",
  },
  {
    id: "RTVE.es@Official",
    tvgId: "RTVE.es",
    name: "RTVE 24h",
    url: "https://www.rtve.es/play/videos/directo/la-1/",
    category: "News",
    country: "ES",
    priority: 80,
    sourceName: "RTVE Official",
    officialUrl: "https://www.rtve.es/play/videos/directo/la-1/",
    officialLabel: "Open RTVE Live",
    kind: "external",
  },
  {
    id: "GloboNews.br@Official",
    tvgId: "GloboNews.br",
    name: "GloboNews",
    url: "https://globoplay.globo.com/globonews/",
    category: "News",
    country: "BR",
    priority: 78,
    sourceName: "Globo Official",
    officialUrl: "https://globoplay.globo.com/globonews/",
    officialLabel: "Open GloboNews Live",
    kind: "external",
  },
  {
    id: "RecordNews.br@Official",
    tvgId: "RecordNews.br",
    name: "Record News",
    url: "https://playplus.com/recordnews/ao-vivo",
    category: "News",
    country: "BR",
    priority: 76,
    sourceName: "Record Official",
    officialUrl: "https://playplus.com/recordnews/ao-vivo",
    officialLabel: "Open Record News Live",
    kind: "external",
  },
  {
    id: "ForoTV.mx@Official",
    tvgId: "ForoTV.mx",
    name: "Foro TV",
    url: "https://www.television.com.mx/envivo/",
    category: "News",
    country: "MX",
    priority: 76,
    sourceName: "Foro TV Official",
    officialUrl: "https://www.television.com.mx/envivo/",
    officialLabel: "Open Foro TV Live",
    kind: "external",
  },
  {
    id: "LasEstrellas.mx@Official",
    tvgId: "LasEstrellas.mx",
    name: "Las Estrellas",
    url: "https://www.lasestrellas.tv/en-vivo",
    category: "General",
    country: "MX",
    priority: 78,
    sourceName: "Las Estrellas Official",
    officialUrl: "https://www.lasestrellas.tv/en-vivo",
    officialLabel: "Open Las Estrellas Live",
    kind: "external",
  },
  {
    id: "TBN.us@Direct",
    tvgId: "TBN.us",
    name: "TBN (Trinity Broadcasting)",
    logo: "https://i.imgur.com/9X8g3K2.png",
    url: "https://api.new.livestream.com/accounts/27460990/events/8265812/live.m3u8",
    category: "Religious",
    country: "US",
    priority: 75,
    sourceName: "TBN Public",
    kind: "direct",
  },
  {
    id: "HopeChannel.us@Direct",
    tvgId: "HopeChannel.us",
    name: "Hope Channel",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://hopetv.org/live/stream/hopeen1/playlist.m3u8",
    category: "Religious",
    country: "US",
    priority: 72,
    sourceName: "Hope Channel Public",
    kind: "direct",
  },
  {
    id: "JewishLifeTV.us@Direct",
    tvgId: "JewishLifeTV.us",
    name: "Jewish Life TV",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://d3thmpcd4qk5ah.cloudfront.net/playlist.m3u8",
    category: "Religious",
    country: "US",
    priority: 68,
    sourceName: "JLTV Public",
    kind: "direct",
  },
  {
    id: "PokerGo.us@Direct",
    tvgId: "PokerGo.us",
    name: "PokerGO",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://pokernightplus.s.llnwi.net/prod/poker-channel.m3u8",
    category: "Sports",
    country: "US",
    priority: 70,
    sourceName: "PokerGO Public",
    kind: "direct",
  },
  {
    id: "ClassicArtsShowcase.us@Direct",
    tvgId: "ClassicArtsShowcase.us",
    name: "Classic Arts Showcase",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://classicarts.akamaized.net/hls/live/2024213/classicarts/master.m3u8",
    category: "Cultural",
    country: "US",
    priority: 68,
    sourceName: "Classic Arts Public",
    kind: "direct",
  },
  {
    id: "RakutenActionMovies.uk@Direct",
    tvgId: "RakutenActionMovies.uk",
    name: "Rakuten Action Movies",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://lds-action-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-lds-action-rakuten/CDN/master.m3u8",
    category: "Movies",
    country: "GB",
    priority: 95,
    sourceName: "Rakuten TV UK",
    kind: "direct",
  },
  {
    id: "RakutenComedyMovies.uk@Direct",
    tvgId: "RakutenComedyMovies.uk",
    name: "Rakuten Comedy Movies",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://lds-comedy-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-lds-comedy-rakuten/CDN/master.m3u8",
    category: "Movies",
    country: "GB",
    priority: 94,
    sourceName: "Rakuten TV UK",
    kind: "direct",
  },
  {
    id: "RakutenDramaMovies.uk@Direct",
    tvgId: "RakutenDramaMovies.uk",
    name: "Rakuten Drama Movies",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://lds-drama-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-lds-drama-rakuten/CDN/master.m3u8",
    category: "Movies",
    country: "GB",
    priority: 93,
    sourceName: "Rakuten TV UK",
    kind: "direct",
  },
  {
    id: "RakutenFamilyMovies.uk@Direct",
    tvgId: "RakutenFamilyMovies.uk",
    name: "Rakuten Family Movies",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://lds-family-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-lds-family-rakuten/CDN/master.m3u8",
    category: "Movies",
    country: "GB",
    priority: 92,
    sourceName: "Rakuten TV UK",
    kind: "direct",
  },
  {
    id: "RakutenTopFree.uk@Direct",
    tvgId: "RakutenTopFree.uk",
    name: "Rakuten Top Free",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://lds-topfree-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-lds-topfree-rakuten/CDN/master.m3u8",
    category: "Movies",
    country: "GB",
    priority: 91,
    sourceName: "Rakuten TV UK",
    kind: "direct",
  },
  {
    id: "PlutoTVCinemaCollection.us@Direct",
    tvgId: "PlutoTVCinemaCollection.us",
    name: "Pluto TV Cinema Collection",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5d/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5d&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 80,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVClassicMovies.us@Direct",
    tvgId: "PlutoTVClassicMovies.us",
    name: "Pluto TV Classic Movies",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5e/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5e&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 80,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVSciFi.us@Direct",
    tvgId: "PlutoTVSciFi.us",
    name: "Pluto TV Sci-Fi",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5f/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5f&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 79,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVNinja.us@Direct",
    tvgId: "PlutoTVNinja.us",
    name: "Pluto TV Ninja",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5g/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5g&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Entertainment",
    country: "US",
    priority: 75,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVMTV.us@Direct",
    tvgId: "PlutoTVMTV.us",
    name: "Pluto TV MTV",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5h/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5h&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Video Channels",
    country: "US",
    priority: 75,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVBET.us@Direct",
    tvgId: "PlutoTVBET.us",
    name: "Pluto TV BET",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5i/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5i&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Entertainment",
    country: "US",
    priority: 74,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVFunnyHa.us@Direct",
    tvgId: "PlutoTVFunnyHa.us",
    name: "Pluto TV Funny Ha",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5j/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5j&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Comedy",
    country: "US",
    priority: 72,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVClassicTV.us@Direct",
    tvgId: "PlutoTVClassicTV.us",
    name: "Pluto TV Classic TV",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5k/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5k&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Classic TV",
    country: "US",
    priority: 72,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVGameShow.us@Direct",
    tvgId: "PlutoTVGameShow.us",
    name: "Pluto TV Game Show",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5l/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5l&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Entertainment",
    country: "US",
    priority: 71,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVKidsAnimation.us@Direct",
    tvgId: "PlutoTVKidsAnimation.us",
    name: "Pluto TV Kids Animation",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5m/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5m&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Kids",
    country: "US",
    priority: 70,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVDocumentary.us@Direct",
    tvgId: "PlutoTVDocumentary.us",
    name: "Pluto TV Documentary",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5n/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5n&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Documentary",
    country: "US",
    priority: 71,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVNews.us@Direct",
    tvgId: "PlutoTVNews.us",
    name: "Pluto TV News",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5o/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5o&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "News",
    country: "US",
    priority: 73,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVScience.us@Direct",
    tvgId: "PlutoTVScience.us",
    name: "Pluto TV Science",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5p/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5p&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Science",
    country: "US",
    priority: 70,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "PlutoTVCrimeDrama.us@Direct",
    tvgId: "PlutoTVCrimeDrama.us",
    name: "Pluto TV Crime Drama",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5q/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5q&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Entertainment",
    country: "US",
    priority: 70,
    sourceName: "Pluto TV US",
    kind: "direct",
  },
  {
    id: "SamsungTVPlusComedy.us@Direct",
    tvgId: "SamsungTVPlusComedy.us",
    name: "Samsung TV Plus Comedy",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5r/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5r&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Comedy",
    country: "US",
    priority: 68,
    sourceName: "Samsung TV Plus US",
    kind: "direct",
  },
  {
    id: "XumoTVMovies.us@Direct",
    tvgId: "XumoTVMovies.us",
    name: "Xumo TV Movies",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5s/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5s&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 68,
    sourceName: "Xumo TV US",
    kind: "direct",
  },
  {
    id: "XumoTVNews.us@Direct",
    tvgId: "XumoTVNews.us",
    name: "Xumo TV News",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5t/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5t&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "News",
    country: "US",
    priority: 67,
    sourceName: "Xumo TV US",
    kind: "direct",
  },
  {
    id: "XumoTVCrime.us@Direct",
    tvgId: "XumoTVCrime.us",
    name: "Xumo TV Crime",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5u/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5u&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Entertainment",
    country: "US",
    priority: 66,
    sourceName: "Xumo TV US",
    kind: "direct",
  },
  {
    id: "XumoTVComedy.us@Direct",
    tvgId: "XumoTVComedy.us",
    name: "Xumo TV Comedy",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5v/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5v&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Comedy",
    country: "US",
    priority: 65,
    sourceName: "Xumo TV US",
    kind: "direct",
  },
  {
    id: "XumoTVSports.us@Direct",
    tvgId: "XumoTVSports.us",
    name: "Xumo TV Sports",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5w/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5w&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Sports",
    country: "US",
    priority: 67,
    sourceName: "Xumo TV US",
    kind: "direct",
  },
  {
    id: "PlexClassicMovies.us@Direct",
    tvgId: "PlexClassicMovies.us",
    name: "Plex Classic Movies",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5x/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5x&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 66,
    sourceName: "Plex US",
    kind: "direct",
  },
  {
    id: "PlexSciFi.us@Direct",
    tvgId: "PlexSciFi.us",
    name: "Plex Sci-Fi",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5y/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5y&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 65,
    sourceName: "Plex US",
    kind: "direct",
  },
  {
    id: "PlexThrillers.us@Direct",
    tvgId: "PlexThrillers.us",
    name: "Plex Thrillers",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5z/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5z&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 65,
    sourceName: "Plex US",
    kind: "direct",
  },
  {
    id: "RokuChannelMovies.us@Direct",
    tvgId: "RokuChannelMovies.us",
    name: "Roku Channel Movies",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5aa/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5aa&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 64,
    sourceName: "Roku Channel US",
    kind: "direct",
  },
  {
    id: "RokuChannelClassicTV.us@Direct",
    tvgId: "RokuChannelClassicTV.us",
    name: "Roku Channel Classic TV",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5bb/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5bb&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Classic TV",
    country: "US",
    priority: 63,
    sourceName: "Roku Channel US",
    kind: "direct",
  },
  {
    id: "RokuChannelKids.us@Direct",
    tvgId: "RokuChannelKids.us",
    name: "Roku Channel Kids",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5cc/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5cc&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Kids",
    country: "US",
    priority: 63,
    sourceName: "Roku Channel US",
    kind: "direct",
  },
  {
    id: "LGChannelsMovies.us@Direct",
    tvgId: "LGChannelsMovies.us",
    name: "LG Channels Movies",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5dd/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5dd&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 63,
    sourceName: "LG Channels US",
    kind: "direct",
  },
  {
    id: "LGChannelsNews.us@Direct",
    tvgId: "LGChannelsNews.us",
    name: "LG Channels News",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5ee/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5ee&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "News",
    country: "US",
    priority: 62,
    sourceName: "LG Channels US",
    kind: "direct",
  },
  {
    id: "TCLChannelMovies.us@Direct",
    tvgId: "TCLChannelMovies.us",
    name: "TCL Channel Movies",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5ff/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5ff&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 62,
    sourceName: "TCL Channel US",
    kind: "direct",
  },
  {
    id: "TCLChannelFamily.us@Direct",
    tvgId: "TCLChannelFamily.us",
    name: "TCL Channel Family",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5gg/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5gg&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Kids",
    country: "US",
    priority: 61,
    sourceName: "TCL Channel US",
    kind: "direct",
  },
  {
    id: "TCLChannelClassic.us@Direct",
    tvgId: "TCLChannelClassic.us",
    name: "TCL Channel Classic TV",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5hh/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5hh&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Classic TV",
    country: "US",
    priority: 61,
    sourceName: "TCL Channel US",
    kind: "direct",
  },
  {
    id: "AiryTVMovies.us@Direct",
    tvgId: "AiryTVMovies.us",
    name: "Airy TV Movies",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5ii/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5ii&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 60,
    sourceName: "Airy TV US",
    kind: "direct",
  },
  {
    id: "AiryTVComedy.us@Direct",
    tvgId: "AiryTVComedy.us",
    name: "Airy TV Comedy",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5jj/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5jj&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Comedy",
    country: "US",
    priority: 59,
    sourceName: "Airy TV US",
    kind: "direct",
  },
  {
    id: "AiryTVSciFi.us@Direct",
    tvgId: "AiryTVSciFi.us",
    name: "Airy TV Sci-Fi",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5kk/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5kk&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 59,
    sourceName: "Airy TV US",
    kind: "direct",
  },
  {
    id: "LocalNowNews.us@Direct",
    tvgId: "LocalNowNews.us",
    name: "Local Now News",
    logo: "https://i.imgur.com/Uk3Zg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5ll/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5ll&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "News",
    country: "US",
    priority: 60,
    sourceName: "Local Now US",
    kind: "direct",
  },
  {
    id: "LocalNowMovies.us@Direct",
    tvgId: "LocalNowMovies.us",
    name: "Local Now Movies",
    logo: "https://i.imgur.com/9XkZg3K.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5mm/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5mm&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Movies",
    country: "US",
    priority: 59,
    sourceName: "Local Now US",
    kind: "direct",
  },
  {
    id: "LocalNowSports.us@Direct",
    tvgId: "LocalNowSports.us",
    name: "Local Now Sports",
    logo: "https://i.imgur.com/8wLjJ2m.png",
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ad9e2d0dd3f4defe4323c5nn/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ad9e2d0dd3f4defe4323c5nn&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=470&terminate=false&userId=",
    category: "Sports",
    country: "US",
    priority: 60,
    sourceName: "Local Now US",
    kind: "direct",
  },
];