export const SKY_STREAM_OVERRIDES = {
  "sky sports main event": "https://live20.bozztv.com/trn03/gin-skysportsmainevent/index.m3u8",
  "sky sports premier league": "https://live20.bozztv.com/trn03/gin-skysportspl/index.m3u8",
  "sky sports football": "https://live20.bozztv.com/trn03/gin-skysportsfootball/index.m3u8",
  "sky sports cricket": "https://live20.bozztv.com/trn03/gin-skysportscricket/index.m3u8",
  "sky sports f1": "https://live20.bozztv.com/trn03/gin-skysportsf1/index.m3u8",
  "sky showcase": "https://live20.bozztv.com/trn03/gin-skyshowcase/index.m3u8",
  "sky news": "https://skynews2-plutolive-vo.akamaized.net/playlist.m3u8",
  "gb news": "https://gbnews-live.rakuten.tv/v1/master.m3u8",
  "talktv": "https://live-talktv.uksse.wurl.tv/playlist.m3u8",
  "bloomberg tv": "https://live.bloomberg.com/kinesis/us-live.m3u8",
  "trt world": "https://trtworld.ios.bund.cpl.delvenetworks.com/playlist.m3u8",
  "tnt sports 1": "https://live20.bozztv.com/trn03/gin-tntsports1/index.m3u8",
  "tnt sports 2": "https://live20.bozztv.com/trn03/gin-tntsports2/index.m3u8",
  "tnt sports 3": "https://live20.bozztv.com/trn03/gin-tntsports3/index.m3u8",
  "tnt sports 4": "https://live20.bozztv.com/trn03/gin-tntsports4/index.m3u8",
  "fox": "https://live20.bozztv.com/trn03/gin-fox/index.m3u8",
  "mbc 1": "https://live20.bozztv.com/trn03/gin-mbc1/index.m3u8",
  "ad sports 1": "https://live20.bozztv.com/trn03/gin-adsports1/index.m3u8",
};
